name: Deploy SQL Scripts
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get -y install postgresql-client
        env:
          POSTGRES_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      - name: Install jq
        run: |
          sudo apt-get -y install jq
      - name: Read script names from JSON
        id: read-scripts
        run: |
          SCRIPTS=$(cat scripts.json | jq -r '.scripts[] | .name')
          STOP_ON_ERROR=$(cat scripts.json | jq -r '.scripts[] | .StopOnError')
          echo "::set-output name=scripts::$SCRIPTS"
          echo "::set-output name=stop-on-error::$STOP_ON_ERROR"
      - name: Execute SQL Scripts
        run: |
          IFS=$'\n'
          for script in ${{ steps.read-scripts.outputs.scripts }}
          do
            script_name=$script
            stop_on_error=$(cat scripts.json | jq -r --arg name "$script_name" '.scripts[] | select(.name == $name) | .StopOnError')
            echo "Executing script: $script_name"
            psql "$POSTGRES_CONNECTION_STRING" -f "$script_name"
            exit_code=$?
            if [ $exit_code -ne 0 ] && [ "$stop_on_error" = "true" ]; then
              echo "Error occurred while executing $script_name. Exiting..."
              exit $exit_code
            fi
          done
